### ISSUE TITLE
Text in the converted PDF file is scaled to look very small on a large page

### ISSUE THREAD

**Issue by ninjayoto** [yakivmospan/github-wikito-converter#18]
@yakivmospan 
Could be related to wkhtmltopdf?
I'm using `wkhtmltox-0.12.4_osx-cocoa-x86-64.pkg`, my mac is set to high resolution (text scaled to be small).
So when I run :
`gwtc ./github-wikito-converter.wiki`

I get pages that look like the image below, nothing like the sample pdfs here in the project

<img width="330" alt="screen shot 2018-03-25 at 3 46 11 pm" src="https://user-images.githubusercontent.com/8582430/37875132-bf69b960-3043-11e8-8278-5f05715a7208.png">

I've reduced the resolution for my mac to see if this has any effect, made the text as large as possible and regenerated the documentation again. but I still get the same result.

Is this something that could be fixed using wikito converter flags?

**Comment by yakivmospan** [comment]
Hey, this is because of [regression issue of wkhtmltopdf on Mac](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3241). Try to use `0.12.3` instead.
