### ISSUE TITLE
Sidebar/TOC longer than the screen doesn't get a scrollbar

### ISSUE THREAD

**Issue by jalovatt** [yakivmospan/github-wikito-converter#20]
As the title suggests - if the generated TOC is too long it flows past the end of the screen with no way to access the items farther down. I imagine it just needs an ```overflow-y: scroll``` somewhere, but this level of HTML is well beyond me.

Cheers.

Example: https://www.dropbox.com/s/yh4ekbz2ul7pk20/Lokasenna_GUI%202.9%20Documentation.html?dl=0

**Comment by yakivmospan** [comment]
Hey, thanks for replying. 

This can be placed somewhere in [html-writer.js](https://github.com/yakivmospan/github-wikito-converter/blob/develop/src/html-writer.js#L60) or in [default](https://github.com/yakivmospan/github-wikito-converter/blob/develop/assets/css/doc.css#L351).

If I will check it out as soon as I found some free time. You can also try to play with it, never late to extend your html skills :) PR's are welcomed.

**Comment by CyborgMaster** [comment]
@yakivmospan, it looks like @jalovatt opened PR for this one at #22, may we get this merge?

**Comment by CyborgMaster** [comment]
@yakivmospan, I added a refinement of #22 in #24 with some spacing improvements.  Please merge that one instead.

**Comment by yakivmospan** [comment]
https://github.com/yakivmospan/github-wikito-converter/releases/tag/1.5.0
