### ISSUE TITLE
Shortcut Links not Hooked Up

### ISSUE THREAD

**Issue by CyborgMaster** [yakivmospan/github-wikito-converter#23]
In GitHub, when writing links between pages, you can omit the wiki link if the page name is the same.

For example: 
``` md
[[Architecture Overview|Architecture-Overview]]
```

is the same as
``` md
[[Architecture Overview]]
```

However, `gwtc` recognizes the second format as a file relative link instead of link within the wiki.

**Comment by yakivmospan** [comment]
Thanks, will jump into it asap.

**Comment by CyborgMaster** [comment]
I have submitted a PR fixing this at #25

**Comment by yakivmospan** [comment]
Yes, I've already left a comment there

**Comment by CyborgMaster** [comment]
Great.  Just wanted to make sure it was clear.  Thanks.

**Comment by yakivmospan** [comment]
No prob, thanks for finding this out ;)

**Comment by yakivmospan** [comment]
https://github.com/yakivmospan/github-wikito-converter/releases/tag/1.5.0
