### ISSUE TITLE
Empty PDF Generated

### ISSUE THREAD

**Issue by petrkalina** [yakivmospan/github-wikito-converter#57]
wanted to report another incidence of problem related to #39, but managed to resolve the problem - see: https://github.com/yakivmospan/github-wikito-converter/issues/39#issuecomment-591603223

sorry for the non-relevant issue and feel free to delete it. Alternatively, you can also use the above instructions to provide a docker image Dockerfile for your tool :-)

**Comment by yakivmospan** [comment]
Hey, thanks! Will add this information to the readme, which will be helpful for ubuntu users. The tool is mostly maintained by community so feel free to make a PR with docker image :) Cheers
