### ISSUE TITLE
Generated PDF file has 0 size

### ISSUE THREAD

**Issue by mcajkovs** [yakivmospan/github-wikito-converter#58]
Problem: Generate PDF file has 0 size and thus no content
OS: Ubuntu 18.04.3 LTS
wkhtmltopdf: 0.12.4
gwtc: 1.5.2

```
mcajkovs@ubuntu:~/wiki$ git clone http://github.com/JustArchiNET/ArchiSteamFarm.wiki.git

mcajkovs@ubuntu:~/wiki$ gwtc -v -f all ./ArchiSteamFarm.wiki
debug:   gwc launched with options format=all, output=./, filename=documentation, title=Documentation , logoImage=null, footer=null, pdfPageCount=null, tocTitle=Table of contents, tocFile=ArchiSteamFarm.wiki/_Sidebar.md, tocLevel=3, highlightTheme=github, userCssFile=null, verbose=true, disableInlineAssets=false
debug:   Found 837 markdown files and 837 links pointing to them in TOC
debug:   Generating html: 33 pages to generate
debug:   Generating pdf: 33 pages to generate

mcajkovs@ubuntu:~/wiki$ ls -la
total 896
drwxrwxr-x  4 mcajkovs mcajkovs   4096 Apr 21 15:34 .
drwxr-xr-x 16 mcajkovs mcajkovs   4096 Apr 21 13:13 ..
drwxrwxr-x  4 mcajkovs mcajkovs   4096 Apr 21 15:27 ArchiSteamFarm.wiki
-rw-rw-r--  1 mcajkovs mcajkovs 829029 Apr 21 15:46 documentation.html
-rw-r--r--  1 mcajkovs mcajkovs      0 Apr 21 15:46 documentation.pdf
```

**Comment by mgoldey** [comment]
Also observed

**Comment by nobicycle** [comment]
also observed
$ gwtc -f pdf -v ./Open-Web-Analytics.wiki-git
debug:   gwc launched with options format=pdf, output=./, filename=documentation, title=Documentation , logoImage=null, footer=null, pdfPageCount=null, tocTitle=Table of contents, tocFile=null, tocLevel=3, highlightTheme=github, userCssFile=null, verbose=true, disableInlineAssets=false
(node:229871) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
debug:   Found 28 markdown files and 28 links pointing to them in TOC
debug:   Generating pdf: 26 pages to generate

**Comment by yakivmospan** [comment]
Hey, sorry guys can't help you here, not using ubuntu. If anyone on ubuntu will figure out the issue - pull requests are welcomed, thanks

**Comment by yakivmospan** [comment]
Oh, actually this issue was mention already in #39 and #57, where @petrkalina found how to fix it by using the docker container.  Please see the [comment](https://github.com/yakivmospan/github-wikito-converter/issues/39#issuecomment-591603223) for more details. Will include this info to the readme with next release.
