### ISSUE TITLE
Highlight.js 9.0 is outdated, the package is broken right now

### ISSUE THREAD

**Issue by lokapal** [yakivmospan/github-wikito-converter#62]
gwtc ./nwchem.wiki
Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
https://github.com/highlightjs/highlight.js/issues/2877
documentation.html

I've tried npm install highlight.js and it says, that 10.5 version is installed. GWTC, obviously, use its own highlight.js

**Comment by panvicka** [comment]
Hello, until fixed I have cloned the repo, changed line 64 in `package.json` to `"highlight.js": "^10.0,"` and installed it as local version as described in README https://github.com/yakivmospan/github-wikito-converter#local-version 

It runs ok again. 

https://github.com/yakivmospan/github-wikito-converter/blob/14b7f30ba9a21feed75fb67e00d80ccfde81315d/package.json#L57-L71

**Comment by yakivmospan** [comment]
Fixed in release [1.5.3] (https://github.com/yakivmospan/github-wikito-converter/releases/tag/1.5.3).
